### ISSUE TITLE
open links with this browser system-wide

### ISSUE THREAD

**Issue by benaryorg** [Dax89/harbour-webpirate#7] opened 2015-01-10 18:53 UTC
As already commented on openrepos.net, it would be great to have support for opening links using webpirate.

It worked using WebCat, by creating a file in /usr/share/applications/.

Links:
https://github.com/llelectronics/webcat/issues/13
https://together.jolla.com/question/1836/set-default-browser/

**Comment by Dax89** [comment] 2015-01-11 12:10
I will try to do it for the version 0.8.7 :)

**Comment by Dax89** [comment] 2015-01-25 16:24
Now it is possible to open links with WebPirate using the link that you have provided (https://together.jolla.com/question/1836/set-default-browser)

I have investigated in order to open a new tab when the browser is already opened: the default browser creates a D-Bus service with an "openUrl" method (the name can be seen in open-url.desktop)

I have managed to create a service for WebPirate too, and I have modified open-url.desktop so it points to the WebPirate's one, but it doesn't works (I don't know why), calling it manually, when the browser is opened, works correctly and opens a new tab with the requested url.

**Comment by MoritzJT** [comment] 2015-05-28 17:06
Is there any progresss on this?

**Comment by Dax89** [comment] 2015-05-28 17:34
It's a Sailfish issue, I can't do anything atm.
The only workaround available is that one linked in this issue!

**Comment by Mikaela** [comment] 2015-07-07 09:38
I have done the workaround, but it appears that there is another issue:

If Webpirate is already open and there is only one tab (more not tested) and you click a link in another application Webpirate is opened, but nothing more happens. I think it should open a new tab including whatever link was clicked.

*I think this might be https://github.com/Dax89/harbour-webpirate/issues/7#issuecomment-71379616 in less technical words.*

**Comment by Dax89** [comment] 2015-07-07 09:47
It's a known issue, and it is related to the default browser issue in Sailfish.

In order to open a new tab, WebPirate needs a DBus service, this one is present in the source code, but is disabled (and untested from about 10 releases) because it is not allowed in the harbour.

**Comment by Dax89** [comment] 2015-08-05 11:51
I have news about this issue!

The commit ce0bded3c025b826d2de61317f7b0c07e40b85e6 restores DBus service and it's only running when WebPirate is active (it seems to be allowed in the harbour, because Tweetian does the same thing), now the problem is different:

**Case 1 (edit harbour-webpirate.desktop)**
```
MimeType=text/html;x-maemo-urischeme/http;x-maemo-urischeme/https;
```
works as always: executing WebPirate instead of Sailfish Browser BUT it does not open new tabs.


**Case 2 (edit open-url.desktop)**
```
# MimeType=text/html;x-maemo-urischeme/http;x-maemo-urischeme/https;

# X-Maemo-Service=org.sailfishos.browser
# X-Maemo-Method=org.sailfishos.browser.openUrl
X-Maemo-Service=org.harbour.webpirate
X-Maemo-Method=org.harbour.webpirate.openUrl
```

If WebPirate is running it creates a new tab BUT when an external link is clicked from another application nothing happens.

I have tried to do Case 1 + Case 2, but Saiflish fallbacks to Case 1.
I'll leave this service active in 1.5 (if it passes the validation!) so anyone is free to make tests!

**Comment by Mikaela** [comment] 2015-09-01 09:57
Is there something preventing the line in `harbour-webpirate.desktop` from being uncommented by default (something in harbour submission rules?)? Currently I must always remember to edit the file after updating Web Pirate.

(Also what is the proper spelling for Web Pirate? I think I change how I spell/write/type it a lot.)

**Comment by Dax89** [comment] 2015-09-01 10:18
Yes, it's about harbour restrictions!


>(Also what is the proper spelling for Web Pirate? I think I change how I spell/write/type it a lot.)

It's ok "WebPirate" and "Web Pirate" too :D

**Comment by benaryorg** [comment] 2015-09-03 23:34
If this is fixed, feel free to close this issue.

**Comment by Mikaela** [comment] 2015-09-04 04:28
It's not, because that one line must always be uncommented after update (even if I am unsure can anything be done to it) and new tabs cannot be opened from external applications if Web Pirate is already open (it only opens Web Pirate with whatever tab you have active).

**Comment by llelectronics** [comment] 2015-10-01 11:49
I think the dbus solution works fine for WebPirate if it would have a "daemon" like dbus service running waiting in the background to start WebPirate even if the UI part is closed. 
This is exactly how Sailfish-Browser does it. The booster-browser is basically listening all the time to the dbus requests.

**Comment by llelectronics** [comment] 2015-10-06 16:25
I have to correct me there. Actually the booster-browser has nothing todo with the dbus calls. Its just a form of preloading the browser libraries for faster startup times. 
What actually is needed is simply a dbus service file describing the dbus service and which file to execute if the service call is made but the application itself is not opened (so basically when WebPirate is closed) 
I was able to make it run just like sailfish-browser with my latest commit in Webcat. 
See: https://github.com/llelectronics/webcat/commit/c09911b4d1abc4a3dd67116994bf315c29825861
This commit is a bit messy and big as I basically copied over your dbus receiver libraries Dax89 which is btw great work again :) 
The actual interesting file is this one: https://github.com/llelectronics/webcat/blob/c09911b4d1abc4a3dd67116994bf315c29825861/org.harbour.webcat.service
This can be easily adapted for webpirate aswell and needs to go into /usr/share/dbus-1/services/ .
Sadly harbour does not allow to put any file into that directory or even /usr/local/share/dbus-1/services/ for that matter. So even if I managed to make a workable solution here we cannot upload it to the Jolla Store. :(

**Comment by Dax89** [comment] 2015-10-06 17:21
@llelectronics Thanks for the extra info!!! :)

Writing the .service file in /.local/share/dbus-1/services overrides sailfish-browser settings too? And it is allowed, in the Harbour?

**Comment by llelectronics** [comment] 2015-10-06 17:28
The .service file does not need to override sailfish-browser settings. 
The only thing that needs to override the open-url.desktop file is the open-url.desktop file with the webpirate dbus calls in ~/.local/share/applications/open-url.desktop 

As for harbour. I don't think it can be shipped in the rpm directly as it would need to ship a hardcoded path /home/nemo which isn't allowed. 
But as you are able in c++ to determine the home directory you could of course just add a button in settings that copies or creates the dbus service file in ~/.local/share/dbus-1/services/ and copies or creates the open-url.desktop file with the dbus X-Maemo-Service and -Method adapted in ~/.local/share/applications 
This open-url.desktop file will then override the global one :)

**Comment by Dax89** [comment] 2015-10-06 17:37
Ok, now it's crystal clear!
It's pretty easy to implement, the "difficult" part was the DBus Interface.

Thanks for your research @llelectronics :)

**Comment by Dax89** [comment] 2015-10-12 09:59
@llelectronics:
This is the implementation: https://github.com/Dax89/harbour-webpirate/commit/2ed95d9bf0b7be9709523060910950b18f6c1204
Fell free to use it in Webcat :)

The problem is: Jolla allows those type of "local" services?

**Comment by llelectronics** [comment] 2015-10-12 10:08
At least th harbour checker should not complain. 
And about the implementation. I think I will use xdg-mime to register a default html handler and create a open-url-webcat.desktop file. That is in my opinion a more correct way of doing it.
You can take a look at https://github.com/llelectronics/mimer/blob/master/src/helper.hpp
To see how I use xdg-mime. 
Currently it needs a linking from mimeapps.list to defaults.list due to an error in the SailfishOS/Mer version of xdg-mime tool.

In general maybe we could work out a standard somehow so that the mimer application will be able to set default apps (not only a webbrowser) with the dbus service file creation.

**Comment by Dax89** [comment] 2015-10-12 10:51
It's ok for me.

About the MIME, do you mean something like this?

```cpp
void DefaultBrowser::overwriteMime()
{
    this->setBusy(true);

    QString desktopfilename = QString("%1.desktop").arg(qApp->applicationName());

    this->setMime("text/html", desktopfilename);
    this->setMime("x-maemo-urischeme/http", desktopfilename);
    this->setMime("x-maemo-urischeme/https", desktopfilename);

    this->setBusy(false);
}

void DefaultBrowser::restoreMime()
{
    this->setBusy(true);

    this->setMime("text/html", "open-url.desktop");
    this->setMime("x-maemo-urischeme/http", "open-url.desktop");
    this->setMime("x-maemo-urischeme/https", "open-url.desktop");

    this->setBusy(false);
}

void DefaultBrowser::setMime(const QString &mimetype, const QString &desktopfile) const
{
    QDir localappsdir = this->localApplicationsDirectory();

    if(!localappsdir.exists("defaults.list"))
    {
        QProcess symlink;
        symlink.start(QString("ln -sf %1 %2").arg(localappsdir.absoluteFilePath("mimeapps.list"), localappsdir.absoluteFilePath("defaults.list")));
        symlink.waitForFinished();
    }

    QProcess xdgmime;
    xdgmime.start(QString("xdg-mime default %1 %2").arg(desktopfile, mimetype));
    xdgmime.waitForFinished();
}
```

**Comment by llelectronics** [comment] 2015-10-12 10:53
Yeah exactly :)

**Comment by Dax89** [comment] 2015-10-12 12:32
Ok, the commit https://github.com/Dax89/harbour-webpirate/commit/3590e31c2882ea8580af3b72d6cb219bccb30c34 uses xdg-mime.

At the current state openUrl() DBus method is called correctly, but if I press a link when the browser is not started nothing happens.

text/html, x-maemo-urischeme/http and x-maemo-urischeme/https MIME types are set to "open-url-webpirate.desktop"

And openurl-webpirate.desktop contains:
```
[Desktop Entry]
Type=Application
Name=Browser
NotShownIn=X-MeeGo;
MimeType=text/html;x-maemo-urischeme/http;x-maemo-urischeme/https;
X-Maemo-Service=org.harbour.webpirate
X-Maemo-Method=org.harbour.webpirate.openUrl
```

The .service is in .local/share/dbus-1/service, and in .local/share/applications I have open-url-webpirate.desktop

Am I missing something?

**Comment by llelectronics** [comment] 2015-10-12 12:46
The folder should be ~/.local/share/dbus-1/service**s** though in the source I think it is correct. 
Hmm... maybe it cached that stuff on my device somehow. Does it work when you put the .service file in /usr/share/dbus-1/services  ?
If it is then its really a caching thing. I would wonder if then will still work if you remove that file from there.

**Comment by Dax89** [comment] 2015-10-12 13:05
Ok fixed in https://github.com/Dax89/harbour-webpirate/commit/01b70a499342e491e4d3c86af0da38260b830492

.service files are case sensitive :D

**Comment by carmenfdezb** [comment] 2015-10-14 14:17
Great!!! I'm testing v1.7-5 and it seems it's working fine ;)

**Comment by Dax89** [comment] 2015-10-14 16:20
Perfect! :+1: 
So I can close this issue.

Fixed in:
1) https://github.com/Dax89/harbour-webpirate/commit/2ed95d9bf0b7be9709523060910950b18f6c1204
2) https://github.com/Dax89/harbour-webpirate/commit/3590e31c2882ea8580af3b72d6cb219bccb30c34
3) https://github.com/Dax89/harbour-webpirate/commit/01b70a499342e491e4d3c86af0da38260b830492

**Closed by Dax89** 2015-10-14 16:20 UTC
Labels: enhancement
