### ISSUE TITLE
Bug in tel link

### ISSUE THREAD

**Issue by eson57** [Dax89/harbour-webpirate#65] opened 2015-10-14 11:34 UTC
Tapping a tel link starts the phone app, but it also opens a web search. Default search engine is Startpage.com.
![screenshot-15-10-14-13-25-45](https://cloud.githubusercontent.com/assets/2996154/10482412/2be7b1aa-7278-11e5-9e9d-994e5e27a58a.png)

**Comment by Dax89** [comment] 2015-10-14 12:09
I can't reproduce, it happens here too?
http://davidwalsh.name/demo/phone-link-protocol.php

**Comment by eson57** [comment] 2015-10-14 12:19
Nope, and I think I can see why. My link looks like this... tel:+46123456789. Yours don't have the +.

**Comment by Dax89** [comment] 2015-10-14 12:39
I have tried even with the "+" prefix, it doesn't trigger the search.

It should be some kind of unhandled case of tel protocol, probably even mailto and sms should be affected of this issue

**Comment by eson57** [comment] 2015-10-14 12:44
mailto protocol seems fine, only tel triggers search. Can you try this tel link...?
https://ootdfashion.com/contact.php

**Comment by Dax89** [comment] 2015-10-14 12:49
Ok now I can reproduce! :)

The issue is in the"target="_self" attribute, page is reloaded by WebKit:
```
<a href="tel:+123456789" target="_self">+123456789</a>
```

It will be fixed in 1.8

**Comment by eson57** [comment] 2015-10-14 12:49
Thanks!  :)

**Closed** 2016-03-08 16:36 UTC
Labels: bug
